export const INDIAN_CITIES = [
  "Agra","Ahmedabad","Aizawl","Ajmer","Aligarh","Alwar","Ambala","Amravati","Amritsar","Anand",
  "Aurangabad","Bangalore","Bareilly","Belgaum","Bhavnagar","Bhopal","Bhubaneswar","Bikaner",
  "Bilaspur","Chandigarh","Chennai","Coimbatore","Cuttack","Daman","Darbhanga","Davangere","Dehradun",
  "Delhi","Dhanbad","Durgapur","Erode","Faridabad","Gandhinagar","Goa","Gorakhpur",
  "Guntur","Gurgaon","Guwahati","Gwalior","Haridwar","Hubli","Hyderabad","Imphal",
  "Indore","Itanagar","Jabalpur","Jaipur","Jalandhar","Jalgaon","Jammu","Jamnagar",
  "Jamshedpur","Jodhpur","Kakinada","Kalyan","Kanpur","Karnal","Kochi","Kohima",
  "Kolhapur","Kolkata","Kota","Kozhikode","Kurnool","Lucknow","Ludhiana","Madurai",
  "Mangalore","Mathura","Meerut","Moradabad","Mumbai","Mysore","Nagpur","Nashik",
  "Navi Mumbai","Noida","Panaji","Patna","Pondicherry","Pune","Raipur","Rajkot",
  "Ranchi","Rohtak","Saharanpur","Salem","Shillong","Shimla","Siliguri","Solapur",
  "Srinagar","Surat","Thane","Thiruvananthapuram","Thrissur","Tiruchirappalli",
  "Tirupati","Tirupur","Ujjain","Vadodara","Varanasi","Vijayawada","Visakhapatnam",
  "Warangal","Agartala","Allahabad","Ambattur","Amroha","Anantapur","Asansol",
  "Bahadurgarh","Bahraich","Ballia","Bally","Banda","Barabanki","Barasat","Bardhaman",
  "Bareilley","Begusarai","Bellary","Bhagalpur","Bharatpur","Bhilai","Bhillwara","Bhiwandi",
  "Bhiwani","Bidar","Bijapur","Bokaro","Bongaigaon","Brahmapur","Bulandshahr",
  "Chandrapur","Chirala","Chittoor","Cuddapah","Deoghar","Dewas","Dibrugarh","Dindigul",
  "Etawah","Firozabad","Gaya","Giridih","Gulbarga","Hapur","Hassan","Hazaribagh",
  "Hisar","Hoshiarpur","Hospet","Hosur","Ichalkaranji","Jhansi","Junagadh","Kadapa",
  "Kalyani","Kamarhati","Karimnagar","Katni","Khammam","Kharagpur","Kirari","Korba",
  "Latur","Loni","Maheshtala","Malegaon","Mango","Manipal","Mandsaur","Medak",
  "Mirzapur","Muzaffarnagar","Muzaffarpur","Nagercoil","Nanded","Nandyal","Narasaraopeta",
  "Nellore","New Delhi","Nizamabad","Pali","Parbhani","Pathankot","Patiala","Phagwara",
  "Pimpri-Chinchwad","Port Blair","Proddatur","Raebareli","Rajahmundry","Rajapalayam",
  "Rajnandgaon","Ramagundam","Rampur","Raurkela","Rewa","Sagar","Sambalpur",
  "Sangli","Satna","Sawai Madhopur","Secunderabad","Shahjahanpur","Shimoga","Silchar",
  "Sirsa","Sitapur","Siwan","Sonipat","South Dumdum","Sri Ganganagar",
  "Tenali","Tezpur","Thoothukudi","Tiruvottiyur","Tumkur","Udaipur","Ulhasnagar",
  "Unnao","Vellore","Yamuna Nagar","Yamunanagar","Yavatmal","Yelahanka","Zirakpur",
].sort();
